# Generated by Django 4.0 on 2024-02-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_mainuser_role_agent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='agents',
        ),
    ]
