# Generated by Django 4.0 on 2024-02-12 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rental.models.apartment
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=rental.models.apartment.apartment_image_path)),
                ('is_video', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.apartment')),
            ],
            options={
                'db_table': 'apartment_images',
            },
        ),
    ]
