# Generated by Django 4.0 on 2024-02-12 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_apartmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_reports', to='rental.agent')),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_reports', to='rental.apartment')),
            ],
            options={
                'db_table': 'visit_reports',
            },
        ),
    ]
