# Generated by Django 4.0 on 2024-02-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_visitreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitreport',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='visitreport',
            old_name='apartment_id',
            new_name='apartment',
        ),
    ]
