# Generated by Django 4.0 on 2024-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_apartmentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
