# Generated by Django 4.0 on 2024-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_remove_apartmentimage_image_apartmentimage_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mainuser',
            index=models.Index(fields=['email', 'username'], name='users_email_12d978_idx'),
        ),
    ]
