# Generated by Django 4.0 on 2024-03-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_mainuser_users_email_12d978_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.CharField(choices=[('Tenant', 'tenant'), ('Owner', 'owner'), ('Agent', 'agent')], max_length=10),
        ),
    ]
