# Generated by Django 4.0 on 2024-03-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_mainuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='assigned_agent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_apartment', to='rental.mainuser'),
        ),
    ]
