# Generated by Django 4.0 on 2024-03-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_apartment_assigned_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='assigned_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_apartment', to='rental.mainuser'),
        ),
    ]
