# Generated by Django 4.0 on 2024-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_remove_apartmentimage_image_url_apartmentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('agent', 'Agent')], max_length=10),
        ),
    ]
