# Generated by Django 4.0 on 2024-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_alter_mainuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='role',
            field=models.CharField(choices=[('Tenant', 'tenant'), ('Owner', 'owner'), ('Agent', 'agent')], max_length=10),
        ),
    ]
