# Generated by Django 4.0 on 2024-03-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_alter_mainuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='assigned_agent',
            new_name='agent',
        ),
    ]
