# Generated by Django 4.0 on 2024-03-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_rename_assigned_agent_apartment_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentreview',
            old_name='user',
            new_name='agent',
        ),
    ]
