# Generated by Django 4.0 on 2024-03-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_rename_user_apartmentreview_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
