# Generated by Django 4.0 on 2024-03-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_rename_end_date_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentreview',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rental.booking'),
            preserve_default=False,
        ),
    ]
