# Generated by Django 4.0 on 2024-03-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_apartmentreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.booking'),
        ),
    ]
